"use client";
// import type { Metadata } from "next";
import { useParams } from "next/navigation";
import { Inter } from "next/font/google";
import axios from "axios";
import "./globals.css";
import {
  Button,
  Flex,
  Card,
  Modal,
  Row,
  Col,
  Form,
  Input,
  InputNumber,
} from "antd";
import Link from "next/link";
import { Provider } from "react-redux";
import { Providers } from "./GlobalRedux/provider";
import { useDispatch, useSelector } from "react-redux";
import {
  increment,
  decrement,
} from "./GlobalRedux/Features/counter/counterSlice";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import React, { useState, useEffect } from "react";
// const dispatch = useDispatch();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="bg-gray-100 min-h-screen">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
