import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button, Flex } from "antd";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navigation = [
  { name: "Post", href: "/post", current: true },
  { name: "Draft", href: "/draft", current: false },
];
function classNames(...classes: any) {
  return classes.filter(Boolean).join(" ");
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container flex p-3 bg-gray-800 shadow-lg justify-between">
          {/* <div className='space-x-4 pt-1 text-center text-white'>WEB Blog</div> */}
          <div className="hidden sm:ml-6 sm:block">
            <div className="flex space-x-4">
              {navigation.map((item) => (
                <a
                  key={item.name}
                  href={item.href}
                  className={classNames(
                    item.current
                      ? "bg-gray-900 text-white px-5"
                      : "text-gray-300 hover:bg-gray-700 hover:text-white",
                    "rounded-md px-3 py-2 text-sm font-medium px-5"
                  )}
                  aria-current={item.current ? "page" : undefined}
                >
                  {item.name}
                </a>
              ))}
            </div>
          </div>
          <div className="hidden sm:ml-6 sm:block">
            <div className="flex space-x-4">
              <Button type="primary">Create Draft</Button>
            </div>
          </div>
        </div>
        <div className="bg-gray-100 min-h-screen">{children}</div>
      </body>
    </html>
  );
}
